#!/bin/bash
COMMAND="/usr/local/bin/sass --color --no-quiet --update"
ROOT="/Users/mjf/dev/mattfeifarek.com/"
SOURCE=$ROOT"src/scss/main.scss"
DEST=$ROOT"src/css/main.css"

echo "$COMMAND $SOURCE $DEST"
$COMMAND $SOURCE $DEST
